### ISSUE TITLE
Getting package error while running test

### ISSUE THREAD

**Issue by HemalathaRamanujam2022** [cofactoryai/textbase#61]
I have installed the packages as given in the ReadMe document. 

poetry run python textbase/textbase_cli.py test --path main.py

But I get "textbase" is not  a package error. Can someone please help?

 File "C:\Users\HEMA S\Python_Projects\textbase\textbase\textbase_cli.py", line 23, in test
    server_path = importlib.resources.files('textbase').joinpath('utils', 'server.py')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMA S\AppData\Local\Programs\Python\Python311\Lib\importlib\resources\_common.py", line 22, in files
    return from_package(get_package(package))
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMA S\AppData\Local\Programs\Python\Python311\Lib\importlib\resources\_common.py", line 55, in get_package
    raise TypeError(f'{package!r} is not a package')
TypeError: 'textbase' is not a package

**Comment by imshourya007** [comment]
the path "C:\Users\HEMA S\Python_Projects\textbase\textbase\textbase_cli.py" are you sure you are installing python and poetry inside correct folder because it seem python is not able to recognise poetry

**Comment by HemalathaRamanujam2022** [comment]
If python is not recognised, I should not be able to see the version under the "textbase" folder, right?


(textbase-client-py3.11) C:\Users\HEMA S\Python_Projects\textbase>python --version
Python 3.11.4

(textbase-client-py3.11) C:\Users\HEMA S\Python_Projects\textbase>poetry --version
Poetry (version 1.6.1)

(textbase-client-py3.11) C:\Users\HEMA S\Python_Projects\textbase>poetry shell
Virtual environment already activated: C:\Users\HEMA S\AppData\Local\pypoetry\Cache\virtualenvs\textbase-client-g5HXBmhY-py3.11

(textbase-client-py3.11) C:\Users\HEMA S\Python_Projects\textbase>poetry install
Updating dependencies
Resolving dependencies...

No dependencies to install or update

Writing lock file

Installing the current project: textbase-client (0.1.2)

(textbase-client-py3.11) C:\Users\HEMA S\Python_Projects\textbase>poetry run python textbase/textbase_cli.py test
Path to the main.py file: main.py
Traceback (most recent call last):
  File "C:\Users\HEMA S\Python_Projects\textbase\textbase\textbase_cli.py", line 201, in <module>
    cli()
  File "C:\Users\HEMA S\AppData\Local\pypoetry\Cache\virtualenvs\textbase-client-g5HXBmhY-py3.11\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMA S\AppData\Local\pypoetry\Cache\virtualenvs\textbase-client-g5HXBmhY-py3.11\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\HEMA S\AppData\Local\pypoetry\Cache\virtualenvs\textbase-client-g5HXBmhY-py3.11\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMA S\AppData\Local\pypoetry\Cache\virtualenvs\textbase-client-g5HXBmhY-py3.11\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMA S\AppData\Local\pypoetry\Cache\virtualenvs\textbase-client-g5HXBmhY-py3.11\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMA S\Python_Projects\textbase\textbase\textbase_cli.py", line 22, in test
    server_path = importlib.resources.files('textbase').joinpath('utils', 'server.py')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMA S\AppData\Local\Programs\Python\Python311\Lib\importlib\resources\_common.py", line 22, in files
    return from_package(get_package(package))
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HEMA S\AppData\Local\Programs\Python\Python311\Lib\importlib\resources\_common.py", line 55, in get_package
    raise TypeError(f'{package!r} is not a package')
TypeError: 'textbase' is not a package

**Comment by KartikeyMish** [comment]
Guys please follow the documentation from [here](https://docs.textbase.ai/get-started/installation)
